# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ffffqlhelperUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources.resource


class Ui_Program(object):
    def setupUi(self, Program):
        Program.setObjectName("Program")
        Program.setWindowModality(QtCore.Qt.NonModal)
        Program.resize(718, 671)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Program.sizePolicy().hasHeightForWidth())
        Program.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Program.setFont(font)
        Program.setStyleSheet("QMainWindow {\n"
"    background-image: url(:/cloth/bgtex.png);\n"
"    background-color: rgb(67, 85, 61);\n"
"}")
        Program.setIconSize(QtCore.QSize(150, 200))
        Program.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Program)
        self.centralwidget.setObjectName("centralwidget")
        self.item_form = QtWidgets.QScrollArea(self.centralwidget)
        self.item_form.setGeometry(QtCore.QRect(390, 240, 321, 351))
        self.item_form.setStyleSheet("QWidget {\n"
"    background-image: url(:/cloth/texpap.png);\n"
"    background-color: rgb(231, 201, 163);\n"
"    border: 1px solid;\n"
"    border-color: rgb(231, 201, 163);\n"
"}\n"
"")
        self.item_form.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.item_form.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.item_form.setWidgetResizable(True)
        self.item_form.setObjectName("item_form")
        self.formContent = QtWidgets.QWidget()
        self.formContent.setGeometry(QtCore.QRect(0, 0, 319, 349))
        self.formContent.setObjectName("formContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.formContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.item_form.setWidget(self.formContent)
        self.items = QtWidgets.QScrollArea(self.centralwidget)
        self.items.setGeometry(QtCore.QRect(10, 50, 371, 541))
        self.items.setStyleSheet("QWidget {\n"
"    background-image: url(:/cloth/texpap.png);\n"
"    background-color: rgb(231, 201, 163);\n"
"    border: 1px solid;\n"
"    border-color:  rgb(231, 201, 163);\n"
"}")
        self.items.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.items.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.items.setWidgetResizable(True)
        self.items.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.items.setObjectName("items")
        self.itemsContent = QtWidgets.QWidget()
        self.itemsContent.setGeometry(QtCore.QRect(0, 0, 369, 539))
        self.itemsContent.setObjectName("itemsContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.itemsContent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.items.setWidget(self.itemsContent)
        self.wikiWidget = QtWidgets.QWidget(self.centralwidget)
        self.wikiWidget.setEnabled(True)
        self.wikiWidget.setGeometry(QtCore.QRect(390, 10, 221, 211))
        self.wikiWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid black;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}")
        self.wikiWidget.setObjectName("wikiWidget")
        self.wikiBtn = QtWidgets.QPushButton(self.wikiWidget)
        self.wikiBtn.setGeometry(QtCore.QRect(0, 0, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Dubai Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.wikiBtn.setFont(font)
        self.wikiBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(51, 102, 204);\n"
"    border-top-left-radius: 15px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius: 10px;\n"
"    border: 2px solid black;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(55, 111, 222);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(47, 95, 190);\n"
"}\n"
"")
        self.wikiBtn.setObjectName("wikiBtn")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(10, 610, 148, 51))
        font = QtGui.QFont()
        font.setFamily("Vin Slab Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setStyleSheet("QPushButton {\n"
"    background-image: url(:/add_btn/add_base.png);\n"
"    background-color: rgb(213, 213, 224);\n"
"    border: 2px solid black;\n"
"    border-radius: 16px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-image: url(:/add_btn/add_hover.png);\n"
"    background-color: rgb(225, 225, 236);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-image: url(:/add_btn/add_active.png);\n"
"    background-color:rgb(193, 193, 202);\n"
"}")
        self.addBtn.setText("")
        self.addBtn.setIconSize(QtCore.QSize(25, 25))
        self.addBtn.setObjectName("addBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(230, 610, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Vin Slab Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.delBtn.setFont(font)
        self.delBtn.setStyleSheet("QPushButton {\n"
"    background-image: url(:/delete_btn/delete_base.png);\n"
"    background-color: rgb(213, 213, 224);\n"
"    border: 2px solid black;\n"
"    border-radius: 16px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-image: url(:/delete_btn/delete_hover.png);\n"
"    background-color: rgb(225, 225, 236);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-image: url(:/delete_btn/delete_active.png);\n"
"    background-color:rgb(193, 193, 202);\n"
"}")
        self.delBtn.setText("")
        self.delBtn.setIconSize(QtCore.QSize(1000, 1000))
        self.delBtn.setObjectName("delBtn")
        self.qualCountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.qualCountBtn.setGeometry(QtCore.QRect(390, 610, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Vin Slab Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.qualCountBtn.setFont(font)
        self.qualCountBtn.setStyleSheet("QPushButton {\n"
"    background-image: url(:/count_btn/count_base.png);\n"
"    background-color: rgb(213, 213, 224);\n"
"    border: 2px solid black;\n"
"    border-radius: 16px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-image: url(:/count_btn/count_hover.png);\n"
"    background-color: rgb(225, 225, 236);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-image: url(:/count_btn/count_active.png);\n"
"    background-color:rgb(193, 193, 202);\n"
"}")
        self.qualCountBtn.setText("")
        self.qualCountBtn.setObjectName("qualCountBtn")
        self.qualityLabel = QtWidgets.QLabel(self.centralwidget)
        self.qualityLabel.setGeometry(QtCore.QRect(600, 610, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.qualityLabel.setFont(font)
        self.qualityLabel.setStyleSheet("QLabel {\n"
"    background-image: url(:/wood/bg_list.png);\n"
"    color: white;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(178, 102, 52);\n"
"}")
        self.qualityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qualityLabel.setObjectName("qualityLabel")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Vin Slab Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.searchBar.setFont(font)
        self.searchBar.setStyleSheet("QLineEdit {\n"
"    background-image: url(:/cloth/texpap3.png);\n"
"    background-color: rgb(216, 188, 153);\n"
"    border-top-left-radius: 10;\n"
"}\n"
"QLineEdit::hover{\n"
"    background-image: url(:/cloth/texpap4.png);\n"
"    background-color: rgb(239, 208, 169);\n"
"}")
        self.searchBar.setAlignment(QtCore.Qt.AlignCenter)
        self.searchBar.setObjectName("searchBar")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(320, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Vin Slab Pro")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.searchBtn.setFont(font)
        self.searchBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(193, 159, 111);\n"
"    border-top-right-radius: 10;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 209, 170);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(197, 171, 139);\n"
"}")
        self.searchBtn.setObjectName("searchBtn")
        self.placeholder = QtWidgets.QLabel(self.centralwidget)
        self.placeholder.setGeometry(QtCore.QRect(10, 590, 371, 16))
        self.placeholder.setStyleSheet("QLabel {\n"
"    background-image: url(:/cloth/texpap.png);\n"
"    background-color: rgb(231, 201, 163);\n"
"    border-bottom-left-radius: 10;\n"
"    border-bottom-right-radius: 10;\n"
"}")
        self.placeholder.setText("")
        self.placeholder.setObjectName("placeholder")
        self.placeholder_2 = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_2.setGeometry(QtCore.QRect(390, 590, 321, 16))
        self.placeholder_2.setStyleSheet("QLabel {\n"
"    background-image: url(:/cloth/texpap.png);\n"
"    background-color: rgb(231, 201, 163);\n"
"    border-bottom-left-radius: 10;\n"
"    border-bottom-right-radius: 10;\n"
"}")
        self.placeholder_2.setText("")
        self.placeholder_2.setObjectName("placeholder_2")
        self.placeholder_3 = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_3.setGeometry(QtCore.QRect(390, 230, 321, 16))
        self.placeholder_3.setStyleSheet("QLabel {\n"
"    background-image: url(:/cloth/texpap.png);\n"
"    background-color: rgb(231, 201, 163);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.placeholder_3.setText("")
        self.placeholder_3.setObjectName("placeholder_3")
        Program.setCentralWidget(self.centralwidget)

        self.retranslateUi(Program)
        QtCore.QMetaObject.connectSlotsByName(Program)

    def retranslateUi(self, Program):
        _translate = QtCore.QCoreApplication.translate
        Program.setWindowTitle(_translate("Program", "MainWindow"))
        self.wikiBtn.setText(_translate("Program", "Wiki"))
        self.qualityLabel.setText(_translate("Program", "_____"))
        self.searchBtn.setText(_translate("Program", "search"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Program = QtWidgets.QMainWindow()
    ui = Ui_Program()
    ui.setupUi(Program)
    Program.show()
    sys.exit(app.exec_())
